name: Feature Request
description: Suggest a new feature or enhancement for Jelly
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🪼
        
        Please provide as much detail as possible about your feature request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: I would like Jelly to support...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Currently, it's difficult to... because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: The feature could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also considered...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful
      placeholder: |
        1. When developing large Roblox games...
        2. When working with multiple packages...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my workflow
        - Critical - Can't use Jelly without this
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this? (Select all that apply)
      options:
        - label: CLI Command
        - label: Configuration Option
        - label: Performance Improvement
        - label: Developer Experience
        - label: Integration (Rojo, Wally, etc.)
        - label: Workspace/Monorepo Support
        - label: Package Management
        - label: Documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this feature request, you agree to the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature would benefit the broader Jelly community, not just my specific use case
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
        - label: I am willing to contribute code for this feature
          required: false
