name: Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Build binaries
      run: |
        npm run build:linux
        npm run build:windows  
        npm run build:mac
        
        # Rename binaries to match Aftman expected format
        cd binaries
        mv jelly-linux jelly-linux-x86_64
        mv jelly-win.exe jelly-windows-x86_64.exe
        mv jelly-macos jelly-macos-x86_64
        
        # Create checksums for Aftman
        sha256sum jelly-linux-x86_64 > jelly-linux-x86_64.sha256
        sha256sum jelly-windows-x86_64.exe > jelly-windows-x86_64.exe.sha256  
        sha256sum jelly-macos-x86_64 > jelly-macos-x86_64.sha256
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          binaries/jelly-linux-x86_64
          binaries/jelly-linux-x86_64.sha256
          binaries/jelly-windows-x86_64.exe
          binaries/jelly-windows-x86_64.exe.sha256
          binaries/jelly-macos-x86_64
          binaries/jelly-macos-x86_64.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
