name: Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Required to upload release assets

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build TypeScript
      run: bun run build
    
    - name: Build binaries
      run: |
        # Get version from tag (remove 'v' prefix)
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Version: $VERSION"
        
        # Create binaries directory
        mkdir -p binaries
        
        # Build each platform with Bun's --compile flag
        
        # Build Linux
        bun build --compile --minify --sourcemap --bytecode --target=bun-linux-x64 ./src/bin/jelly.ts --outfile ./binaries/jelly-linux
        
        # Build Windows  
        bun build --compile --minify --sourcemap --bytecode --target=bun-windows-x64 ./src/bin/jelly.ts --outfile ./binaries/jelly.exe
        
        # Build macOS
        bun build --compile --minify --sourcemap --bytecode --target=bun-darwin-x64 ./src/bin/jelly.ts --outfile ./binaries/jelly-macos
        
        # List what we have
        ls -la binaries/
        
        # Now zip everything with proper names
        cd binaries
        
        # Zip Linux binary
        if [ -f "jelly-linux" ]; then
          zip "jelly-${VERSION}-linux-x86_64.zip" jelly-linux
          rm jelly-linux
        fi
        
        # Zip Windows binary
        if [ -f "jelly.exe" ]; then
          zip "jelly-${VERSION}-windows-x86_64.zip" jelly.exe
          rm jelly.exe
        fi
        
        # Zip macOS binary
        if [ -f "jelly-macos" ]; then
          zip "jelly-${VERSION}-macos-x86_64.zip" jelly-macos
          rm jelly-macos
        fi
        
        # List final files
        ls -la
        
        # Create checksums for Aftman
        for file in *.zip; do
          if [ -f "$file" ]; then
            sha256sum "$file" > "${file}.sha256"
          fi
        done
    
    - name: Upload Release Assets
      run: |
        # Get version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Upload all zip files and their checksums
        gh release upload ${{ github.event.release.tag_name }} \
          binaries/jelly-${VERSION}-linux-x86_64.zip \
          binaries/jelly-${VERSION}-linux-x86_64.zip.sha256 \
          binaries/jelly-${VERSION}-windows-x86_64.zip \
          binaries/jelly-${VERSION}-windows-x86_64.zip.sha256 \
          binaries/jelly-${VERSION}-macos-x86_64.zip \
          binaries/jelly-${VERSION}-macos-x86_64.zip.sha256 \
          --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
