-- 🪼 Auto-generated by Jelly
-- This file provides access to installed packages

local Packages = {}

Packages["evaera/promise"] = require("@self/evaera_promise")
Packages["omouta/rex"] = require("@self/omouta_rex")

return Packages
